language: node_js
node_js:
  - "9"
before_script:
  - npm install -g gitbook-cli
script: gitbook install && gitbook build
deploy:
  local-dir: _book
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master